
import { Category, Flashcard, CategoryKey } from './types';

export const CATEGORIES: Category[] = [
  { id: 'verbs_essentials', label: 'Verbos: Essenciais', icon: '✨' },
  { id: 'prepositions_essentials', label: 'Preposições Essenciais', icon: '🔗' },
  { id: 'expressions_daily', label: 'Expressões: Dia a Dia', icon: '🗣️' },
  { id: 'expressions_verbs', label: 'Expressões: Verbos', icon: '⚡' },
  { id: 'expressions_routine', label: 'Expressões: Rotina', icon: '⏰' },
  { id: 'expressions_conversation', label: 'Expressões: Conversa', icon: '💬' },
  { id: 'expressions_quick', label: 'Expressões: Rápidas', icon: '🚀' },
  { id: 'expressions_situations', label: 'Expressões: Situações', icon: '📍' },
  { id: 'expressions_emotions', label: 'Expressões: Emoções', icon: '🎭' },
  { id: 'pronouns_subject', label: 'Pronomes Sujeito', icon: '👤' },
  { id: 'pronouns_object', label: 'Pronomes Objeto', icon: '🎯' },
  { id: 'possessive_adj', label: 'Adjetivos Possessivos', icon: '🏠' },
  { id: 'possessive_pron', label: 'Pronomes Possessivos', icon: '💎' },
  { id: 'reflexive_pron', label: 'Pronomes Reflexivos', icon: '🪞' },
  { id: 'professions', label: 'Profissões', icon: '💼' },
  { id: 'numbers', label: 'Números', icon: '🔢' },
  { id: 'question_words', label: 'Perguntas', icon: '❓' },
  { id: 'days_of_week', label: 'Dias da Semana', icon: '📅' },
  { id: 'verbs_comm', label: 'Verbos: Comunicação', icon: '🗣️' },
  { id: 'verbs_routine', label: 'Verbos: Rotina', icon: '🏃' },
  { id: 'verbs_perception', label: 'Verbos: Sentidos', icon: '👁️' },
  { id: 'verbs_other', label: 'Verbos: Úteis', icon: '💼' },
  { id: 'fruits', label: 'Frutas', icon: '🍎' },
  { id: 'insects', label: 'Insetos', icon: '🐞' },
  { id: 'transport', label: 'Transportes', icon: '🚗' },
  { id: 'feelings', label: 'Sentimentos', icon: '😊' },
  { id: 'seasons', label: 'Natureza', icon: '🌻' },
  { id: 'months', label: 'Meses', icon: '📅' },
  { id: 'body', label: 'Corpo', icon: '👤' },
  { id: 'farm_animals', label: 'Fazenda', icon: '🐄' },
  { id: 'wild_animals', label: 'Selvagens', icon: '🦁' },
  { id: 'sea_animals', label: 'Marinhos', icon: '🌊' },
  { id: 'personal_accessories', label: 'Acessórios', icon: '🕶️' },
  { id: 'nature_others', label: 'Outros', icon: '🐦' },
];

export const FLASHCARDS: Record<CategoryKey, Flashcard[]> = {
  favorites: [],
  difficult: [], 
  custom_list: [],
  prepositions_essentials: [
    { pt: "Em / dentro", en: "In" },
    { pt: "Em / sobre / em cima", en: "On" },
    { pt: "Em / no / na (lugares específicos)", en: "At" },
    { pt: "Para", en: "To" },
    { pt: "De / a partir de", en: "From" },
    { pt: "Com", en: "With" },
    { pt: "Sobre / a respeito de", en: "About" },
    { pt: "Para / por", en: "For" },
    { pt: "Depois de", en: "After" },
    { pt: "Antes de", en: "Before" },
    { pt: "Entre (duas coisas)", en: "Between" },
    { pt: "Sobre / acima / por cima", en: "Over" }
  ],
  expressions_daily: [
    { pt: "Como você está?", en: "How are you?" },
    { pt: "Qual é o seu nome?", en: "What’s your name?" },
    { pt: "Prazer em conhecê-lo.", en: "Nice to meet you." },
    { pt: "De onde você é?", en: "Where are you from?" },
    { pt: "Quantos anos você tem?", en: "How old are you?" },
    { pt: "Eu não sei.", en: "I don’t know." },
    { pt: "Eu não entendo.", en: "I don’t understand." },
    { pt: "Você pode me ajudar?", en: "Can you help me?" },
    { pt: "Eu preciso de ajuda.", en: "I need help." },
    { pt: "Me desculpe.", en: "I’m sorry." },
    { pt: "Obrigado.", en: "Thank you." },
    { pt: "De nada.", en: "You’re welcome." },
    { pt: "Com licença.", en: "Excuse me." },
    { pt: "Que horas são?", en: "What time is it?" },
    { pt: "Até mais tarde.", en: "See you later." },
    { pt: "Se cuida.", en: "Take care." },
    { pt: "O que você quer dizer?", en: "What do you mean?" },
    { pt: "Não importa.", en: "It doesn’t matter." },
    { pt: "Sem problemas.", en: "No problem." },
    { pt: "É isso. / Pronto.", en: "That’s it." }
  ],
  expressions_verbs: [
    { pt: "Eu não tenho isso.", en: "I don’t have it." },
    { pt: "Eu não quero isso.", en: "I don’t want it." },
    { pt: "Não faço ideia.", en: "I have no idea." },
    { pt: "Estou procurando...", en: "I’m looking for..." },
    { pt: "Eu encontrei.", en: "I found it." },
    { pt: "Eu perdi.", en: "I lost it." },
    { pt: "Eu preciso disso.", en: "I need it." },
    { pt: "Entendi / Peguei.", en: "I got it." },
    { pt: "Falo sério.", en: "I mean it." },
    { pt: "Eu sabia!", en: "I knew it!" },
    { pt: "Deixe-me ver.", en: "Let me see." },
    { pt: "Deixe-me pensar.", en: "Let me think." },
    { pt: "Vamos!", en: "Let’s go!" },
    { pt: "Vamos fazer isso!", en: "Let’s do it!" },
    { pt: "Aqui está.", en: "Here you go." },
    { pt: "Isso! / Pronto!", en: "There you go." },
    { pt: "Venha comigo.", en: "Come with me." },
    { pt: "Me dê um segundo.", en: "Give me a second." },
    { pt: "Espere um minuto.", en: "Wait a minute." },
    { pt: "Leve o tempo que precisar.", en: "Take your time." }
  ],
  expressions_routine: [
    { pt: "Acordar.", en: "Wake up." },
    { pt: "Levantar da cama.", en: "Get up." },
    { pt: "Se apronte / prepare-se.", en: "Get ready." },
    { pt: "Anda logo!", en: "Hurry up." },
    { pt: "Depressa.", en: "Hurry." },
    { pt: "Calma.", en: "Calm down." },
    { pt: "Sente-se.", en: "Sit down." },
    { pt: "Levante-se.", en: "Stand up." },
    { pt: "Entre.", en: "Come in." },
    { pt: "Sair.", en: "Go out." },
    { pt: "Voltar.", en: "Come back." },
    { pt: "Retornar.", en: "Go back." },
    { pt: "Ligar.", en: "Turn on." },
    { pt: "Desligar.", en: "Turn off." },
    { pt: "Pegar / recolher.", en: "Pick up." },
    { pt: "Colocar / abaixar.", en: "Put down." },
    { pt: "Vestir / colocar.", en: "Put on." },
    { pt: "Tirar / decolar.", en: "Take off." },
    { pt: "Vá mais devagar.", en: "Slow down." },
    { pt: "Tenha cuidado.", en: "Be careful." },
    { pt: "Preste atenção.", en: "Pay attention." }
  ],
  expressions_conversation: [
    { pt: "Eu concordo.", en: "I agree." },
    { pt: "Eu discordo.", en: "I disagree." },
    { pt: "Você tem certeza?", en: "Are you sure?" },
    { pt: "Tenho certeza.", en: "I’m sure." },
    { pt: "Não tenho certeza.", en: "I’m not sure." },
    { pt: "Depende.", en: "It depends." },
    { pt: "Claro!", en: "Of course!" },
    { pt: "Na verdade, não.", en: "Not really." },
    { pt: "Talvez mais tarde.", en: "Maybe later." },
    { pt: "Acho que sim.", en: "I think so." },
    { pt: "Acho que não.", en: "I don’t think so." },
    { pt: "Isso é verdade.", en: "That’s true." },
    { pt: "Isso não é verdade.", en: "That’s not true." },
    { pt: "Espero que sim.", en: "I hope so." },
    { pt: "Espero que não.", en: "I hope not." },
    { pt: "Entendi você.", en: "I got you." },
    { pt: "Faz sentido.", en: "It makes sense." },
    { pt: "Não faz sentido.", en: "It doesn’t make sense." },
    { pt: "Estou brincando.", en: "I’m just kidding." },
    { pt: "Não se preocupe.", en: "Don’t worry." }
  ],
  expressions_quick: [
    { pt: "O que está acontecendo?", en: "What’s going on?" },
    { pt: "O que aconteceu?", en: "What happened?" },
    { pt: "Vamos! / Poxa!", en: "Come on!" },
    { pt: "Espere aí.", en: "Hold on." },
    { pt: "O que há de errado?", en: "What’s wrong?" },
    { pt: "E aí? / Novidades?", en: "What’s up?" },
    { pt: "Deixa pra lá.", en: "Never mind." },
    { pt: "Esquece.", en: "Forget it." },
    { pt: "Sim, com certeza.", en: "Absolutely." },
    { pt: "Combinado.", en: "Deal." },
    { pt: "Exatamente / Isso mesmo.", en: "Exactly." },
    { pt: "É mesmo? / Verdade?", en: "Really?" },
    { pt: "Sim, definitivamente", en: "Definitely." },
    { pt: "Com certeza!", en: "For sure" }
  ],
  expressions_situations: [
    { pt: "Estou com fome.", en: "I’m hungry." },
    { pt: "Estou com sede.", en: "I’m thirsty." },
    { pt: "Estou cansado.", en: "I’m tired." },
    { pt: "Estou ocupado.", en: "I’m busy." },
    { pt: "Estou entediado.", en: "I’m bored." },
    { pt: "Estou pronto.", en: "I’m ready." },
    { pt: "Estou em casa.", en: "I’m home." },
    { pt: "Estou indo.", en: "I’m coming." }
  ],
  expressions_emotions: [
    { pt: "Estou feliz.", en: "I’m happy." },
    { pt: "Estou triste.", en: "I’m triste." },
    { pt: "Estou bravo.", en: "I’m angry." },
    { pt: "Estou animado.", en: "I’m excited." }
  ],
  pronouns_subject: [
    { pt: "Eu", en: "I" },
    { pt: "Você / Tu", en: "You" },
    { pt: "Ele", en: "He" },
    { pt: "Ela", en: "She" },
    { pt: "Ele / Ela (Neutro/Objeto)", en: "It" },
    { pt: "Nós", en: "We" },
    { pt: "Vocês / Vós", en: "You" },
    { pt: "Eles / Elas", en: "They" }
  ],
  pronouns_object: [
    { pt: "Me / Mim", en: "Me" },
    { pt: "Te / Você", en: "You" },
    { pt: "O / Ele", en: "Him" },
    { pt: "A / Ela", en: "Her" },
    { pt: "O / A (Neutro/Objeto)", en: "It" },
    { pt: "Nos / Nós", en: "Us" },
    { pt: "Vocês / Vos", en: "You" },
    { pt: "Os / As / Eles / Elas", en: "Them" }
  ],
  possessive_adj: [
    { pt: "Meu / Minha", en: "My" },
    { pt: "Seu / Sua / Teu", en: "Your" },
    { pt: "Dele / Seu", en: "His" },
    { pt: "Dela / Sua", en: "Her" },
    { pt: "Dele / Dela (Neutro)", en: "Its" },
    { pt: "Nosso / Nossa", en: "Our" },
    { pt: "Vosso / Seu / Sua", en: "Your" },
    { pt: "Deles / Delas", en: "Their" }
  ],
  possessive_pron: [
    { pt: "Meu / Minha (Final de frase)", en: "Mine" },
    { pt: "Seu / Sua (Final de frase)", en: "Yours" },
    { pt: "Dele / Seu (Final de frase)", en: "His" },
    { pt: "Dela / Sua (Final de frase)", en: "Hers" },
    { pt: "Dele / Dela (Neutro) (Final de frase)", en: "Its" },
    { pt: "Nosso / Nossa (Final de frase)", en: "Ours" },
    { pt: "Seu / Sua (Final de frase)", en: "Yours" },
    { pt: "Deles / Delas (Final de frase)", en: "Theirs" }
  ],
  reflexive_pron: [
    { pt: "Eu mesmo(a)", en: "Myself" },
    { pt: "Você mesmo(a)", en: "Yourself" },
    { pt: "Ele mesmo", en: "Himself" },
    { pt: "Ela mesma", en: "Herself" },
    { pt: "Ele/Ela mesmo(a) (Neutro)", en: "Itself" },
    { pt: "Nós mesmos(as)", en: "Ourselves" },
    { pt: "Vocês mesmos(as)", en: "Yourselves" },
    { pt: "Eles/Elas mesmos(as)", en: "Themselves" }
  ],
  professions: [
    { pt: "Professor(a)", en: "Teacher" },
    { pt: "Médico(a)", en: "Doctor" },
    { pt: "Dentista", en: "Dentist" },
    { pt: "Advogado(a)", en: "Lawyer" },
    { pt: "Engenheiro(a)", en: "Engineer" },
    { pt: "Secretário(a)", en: "Secretary" },
    { pt: "Gerente", en: "Manager" },
    { pt: "Vendedor(a)", en: "Salesperson" },
    { pt: "Empregado(a) de mesa", en: "Waiter / Waitress" },
    { pt: "Motorista", en: "Driver" },
    { pt: "Mecânico(a)", en: "Mechanic" },
    { pt: "Cabeleireiro(a)", en: "Hairdresser" },
    { pt: "Fazendeiro(a)", en: "Farmer" },
    { pt: "Padeiro(a)", en: "Baker" },
    { pt: "Escritor(a)", en: "Writer" },
    { pt: "Ator / Atriz", en: "Actor / Actress" },
    { pt: "Músico(a)", en: "Musician" },
    { pt: "Programador(a)", en: "Programmer" },
    { pt: "Fotógrafo(a)", en: "Photographer" },
    { pt: "Arquiteto(a)", en: "Architect" }
  ],
  numbers: [
    { pt: "Zero", en: "Zero" },
    { pt: "Um", en: "One" },
    { pt: "Dois", en: "Two" },
    { pt: "Três", en: "Three" },
    { pt: "Quatro", en: "Four" },
    { pt: "Cinco", en: "Five" },
    { pt: "Seis", en: "Six" },
    { pt: "Sete", en: "Seven" },
    { pt: "Oito", en: "Eight" },
    { pt: "Nove", en: "Nine" },
    { pt: "Dez", en: "Ten" },
    { pt: "Onze", en: "Eleven" },
    { pt: "Doze", en: "Twelve" },
    { pt: "Treze", en: "Thirteen" },
    { pt: "Quatorze", en: "Fourteen" },
    { pt: "Quinze", en: "Fifteen" },
    { pt: "Dezesseis", en: "Sixteen" },
    { pt: "Dezessete", en: "Seventeen" },
    { pt: "Dezoito", en: "Eighteen" },
    { pt: "Dezenove", en: "Nineteen" },
    { pt: "Vinte", en: "Twenty" },
    { pt: "Trinta", en: "Thirty" },
    { pt: "Quarenta", en: "Forty" },
    { pt: "Cinquenta", en: "Fifty" },
    { pt: "Sessenta", en: "Sixty" },
    { pt: "Setenta", en: "Seventy" },
    { pt: "Oitenta", en: "Eighty" },
    { pt: "Noventa", en: "Ninety" },
    { pt: "Cem", en: "One Hundred" },
    { pt: "Duzentos", en: "Two Hundred" },
    { pt: "Trezentos", en: "Three Hundred" },
    { pt: "Quatrocentos", en: "Four Hundred" },
    { pt: "Quinhentos", en: "Five Hundred" },
    { pt: "Seiscentos", en: "Six Hundred" },
    { pt: "Setecentos", en: "Seven Hundred" },
    { pt: "Oitocentos", en: "Eight Hundred" },
    { pt: "Novecentos", en: "Nine Hundred" },
    { pt: "Mil", en: "One Thousand" }
  ],
  days_of_week: [
    { pt: "Segunda-feira", en: "Monday" },
    { pt: "Terça-feira", en: "Tuesday" },
    { pt: "Quarta-feira", en: "Wednesday" },
    { pt: "Quinta-feira", en: "Thursday" },
    { pt: "Sexta-feira", en: "Friday" },
    { pt: "Sábado", en: "Saturday" },
    { pt: "Domingo", en: "Sunday" }
  ],
  question_words: [
    { pt: "O que / Qual", en: "What" },
    { pt: "Quem", en: "Who" },
    { pt: "Onde", en: "Where" },
    { pt: "Quando", en: "When" },
    { pt: "Por que", en: "Why" },
    { pt: "Qual (escolha)", en: "Which" },
    { pt: "De quem", en: "Whose" },
    { pt: "Como", en: "How" }
  ],
  verbs_essentials: [
    { pt: "Ser ou Estar", en: "To Be" },
    { pt: "Ter", en: "To Have" },
    { pt: "Fazer (executar)", en: "To Do" },
    { pt: "Fazer (criar)", en: "To Make" },
    { pt: "Ir", en: "To Go" },
    { pt: "Conseguir/Pegar/Chegar", en: "To Get" },
    { pt: "Dizer", en: "To Say" },
    { pt: "Contar/Dizer para alguém", en: "To Tell" },
    { pt: "Levar/Pegar", en: "To Take" },
    { pt: "Dar", en: "To Give" }
  ],
  verbs_comm: [
    { pt: "Saber/Conhecer", en: "To Know" },
    { pt: "Pensar/Achar", en: "To Think" },
    { pt: "Querer", en: "To Want" },
    { pt: "Precisar", en: "To Need" },
    { pt: "Gostar", en: "To Like" },
    { pt: "Amar", en: "To Love" },
    { pt: "Perguntar/Pedir", en: "To Ask" },
    { pt: "Responder", en: "To Answer" },
    { pt: "Falar", en: "To Speak" },
    { pt: "Entender", en: "To Understand" }
  ],
  verbs_routine: [
    { pt: "Vir", en: "To Come" },
    { pt: "Sair/Deixar/Partir", en: "To Leave" },
    { pt: "Trabalhar/Funcionar", en: "To Work" },
    { pt: "Dormir", en: "To Sleep" },
    { pt: "Comer", en: "To Eat" },
    { pt: "Beber", en: "To Drink" },
    { pt: "Andar", en: "To Walk" },
    { pt: "Correr", en: "To Run" },
    { pt: "Ajudar", en: "To Help" },
    { pt: "Jogar/Brincar/Tocar", en: "To Play" }
  ],
  verbs_perception: [
    { pt: "Ver", en: "To See" },
    { pt: "Olhar", en: "To Look" },
    { pt: "Assistir", en: "To Watch" },
    { pt: "Escutar (atenção)", en: "To Listen" },
    { pt: "Ouvir (som)", en: "To Hear" },
    { pt: "Sentir", en: "To Feel" },
    { pt: "Usar", en: "To Use" },
    { pt: "Tentar", en: "To Try" }
  ],
  verbs_other: [
    { pt: "Comprar", en: "To Buy" },
    { pt: "Vender", en: "To Sell" },
    { pt: "Chamar/Ligar", en: "To Call" },
    { pt: "Encontrar", en: "To Find" },
    { pt: "Perder", en: "To Lose" },
    { pt: "Manter/Guardar", en: "To Keep" },
    { pt: "Colocar", en: "To Put" },
    { pt: "Mostrar", en: "To Show" },
    { pt: "Começar", en: "To Start" },
    { pt: "Parar", en: "To Stop" },
    { pt: "Esperar", en: "To Wait" },
    { pt: "Viver/Morar", en: "To Live" }
  ],
  fruits: [
    { pt: "Maçã", en: "Apple" },
    { pt: "Banana", en: "Banana" },
    { pt: "Laranja", en: "Orange" },
    { pt: "Morango", en: "Strawberry" },
    { pt: "Uva", en: "Grape" },
    { pt: "Melancia", en: "Watermelon" },
    { pt: "Abacaxi", en: "Pineapple" },
    { pt: "Pêra", en: "Pear" },
    { pt: "Mamão", en: "Papaya" },
    { pt: "Manga", en: "Mango" },
    { pt: "Limão", en: "Lemon" },
    { pt: "Cereja", en: "Cherry" }
  ],
  insects: [
    { pt: "Borboleta", en: "Butterfly" }, { pt: "Joaninha", en: "Ladybug" }, { pt: "Lagarta", en: "Caterpillar" },
    { pt: "Abelha", en: "Bee" }, { pt: "Libélula", en: "Dragonfly" }, { pt: "Vagalume", en: "Firefly" },
    { pt: "Mosca", en: "Fly" }, { pt: "Aranha", en: "Spider" }, { pt: "Grilo", en: "Cricket" },
    { pt: "Formiga", en: "Ant" }, { pt: "Besouro", en: "Beetle" }, { pt: "Barata", en: "Cockroach" }
  ],
  transport: [
    { pt: "Bicicleta", en: "Bicycle" }, { pt: "Carro", en: "Car" }, { pt: "Moto", en: "Motorcycle" },
    { pt: "Ônibus", en: "Bus" }, { pt: "Caminhão", en: "Truck" }, { pt: "Tractor", en: "Tractor" },
    { pt: "Trem", en: "Train" }, { pt: "Barco", en: "Boat" }, { pt: "Navio", en: "Ship" },
    { pt: "Lancha", en: "Speedboat" }, { pt: "Canoa", en: "Canoe" }, { pt: "Helicóptero", en: "Helicopter" },
    { pt: "Avião", en: "Airplane" }, { pt: "Balão de Ar Quente", en: "Hot Air Balloon" }, { pt: "Foguete", en: "Rocket" }
  ],
  feelings: [
    { pt: "Feliz", en: "Happy" }, { pt: "Triste", en: "Sad" }, { pt: "Animado", en: "Excited" },
    { pt: "Bravo/Irritado", en: "Angry" }, { pt: "Confuso", en: "Confused" }, { pt: "Preocupado", en: "Worried" },
    { pt: "Confiante", en: "Confident" }, { pt: "Estressado", en: "Stressed" }, { pt: "Engraçado", en: "Funny" }
  ],
  seasons: [
    { pt: "Primavera", en: "Spring" }, { pt: "Flor", en: "Flower" }, { pt: "Chuva", en: "Rain" },
    { pt: "Arco-íris", en: "Rainbow" }, { pt: "Verão", en: "Summer" }, { pt: "Sol", en: "Sun" },
    { pt: "Praia", en: "Beach" }, { pt: "Outono", en: "Autumn / Fall" }, { pt: "Folhas", en: "Leaves" },
    { pt: "Vento", en: "Wind" }, { pt: "Inverno", en: "Winter" }, { pt: "Neve", en: "Snow" }, { pt: "Luvas", en: "Gloves" }
  ],
  months: [
    { pt: "Janeiro", en: "January" }, { pt: "Fevereiro", en: "February" }, { pt: "Março", en: "March" },
    { pt: "Abril", en: "April" }, { pt: "Maio", en: "May" }, { pt: "Junho", en: "June" },
    { pt: "Julho", en: "July" }, { pt: "Agosto", en: "August" }, { pt: "Setembro", en: "September" },
    { pt: "Outubro", en: "October" }, { pt: "Novembro", en: "November" }, { pt: "Dezembro", en: "December" }
  ],
  body: [
    { pt: "Corpo", en: "Body" }, { pt: "Cabeça", en: "Head" }, { pt: "Tronco", en: "Torso" },
    { pt: "Tórax / Peito", en: "Chest" }, { pt: "Ombro", en: "Shoulder" }, { pt: "Braço", en: "Arm" },
    { pt: "Cotovelo", en: "Elbow" }, { pt: "Mão", en: "Hand" }, { pt: "Dedos da Mão", en: "Fingers" },
    { pt: "Barriga", en: "Belly" }, { pt: "Cintura", en: "Waist" }, { pt: "Costas", en: "Back" },
    { pt: "Perna", en: "Leg" }, { pt: "Coxa", en: "Thigh" }, { pt: "Joelho", en: "Knee" },
    { pt: "Pé", en: "Foot" }, { pt: "Pés (Plural)", en: "Feet" }, { pt: "Dedos do Pé", en: "Toes" }
  ],
  farm_animals: [
    { pt: "Vaca", en: "Cow" }, { pt: "Cavalo", en: "Horse" }, { pt: "Porco", en: "Pig" },
    { pt: "Ovelha", en: "Sheep" }, { pt: "Cabra", en: "Goat" }, { pt: "Galinha", en: "Hen" },
    { pt: "Galo", en: "Rooster" }, { pt: "Pato", en: "Duck" }, { pt: "Coelho", en: "Rabbit" },
    { pt: "Cachorro", en: "Dog" }, { pt: "Gato", en: "Cat" }
  ],
  wild_animals: [
    { pt: "Leão", en: "Lion" }, { pt: "Elefante", en: "Elephant" }, { pt: "Girafa", en: "Giraffe" },
    { pt: "Macaco", en: "Monkey" }, { pt: "Crocodilo", en: "Crocodile" }, { pt: "Tigre", en: "Tiger" },
    { pt: "Gorila", en: "Gorilla" }, { pt: "Zebra", en: "Zebra" }, { pt: "Rinoceronte", en: "Rhinoceros" },
    { pt: "Urso", en: "Bear" }, { pt: "Lobo", en: "Wolf" }, { pt: "Guepardo", en: "Cheetah" }
  ],
  sea_animals: [
    { pt: "Peixe", en: "Fish" }, { pt: "Golfinho", en: "Dolphin" }, { pt: "Tartaruga Marinha", en: "Sea Turtle" },
    { pt: "Polvo", en: "Octopus" }, { pt: "Tubarão", en: "Shark" }, { pt: "Estrela do Mar", en: "Starfish" },
    { pt: "Baleia", en: "Whale" }, { pt: "Foca", en: "Seal" }, { pt: "Lula", en: "Squid" }
  ],
  nature_others: [
    { pt: "Pássaro", en: "Bird" }, { pt: "Pinguim", en: "Penguin" }, { pt: "Sol", en: "Sun" }
  ],
  personal_accessories: [
    { pt: "Chapéu", en: "Hat" },
    { pt: "Boné", en: "Cap" },
    { pt: "Cachecol", en: "Scarf" },
    { pt: "Cinto", en: "Belt" },
    { pt: "Óculos de Sol", en: "Sunglasses" },
    { pt: "Óculos", en: "Glasses" },
    { pt: "Luvas", en: "Gloves" },
    { pt: "Anel", en: "Ring" },
    { pt: "Guarda-chuva", en: "Umbrella" },
    { pt: "Relógio (de pulso)", en: "Watch" }
  ]
};
